language: ruby
rvm:
  - 2.1.5
install: bundle install --path .bundle --jobs=3 --retry=3
cache:
  directories:
  - .bundle
env:
  - CODECLIMATE_REPO_TOKEN=8259e5b926031e84ed19c7a1a5c42e256fa9a11c2b4cf1457f5a36a45a239ca7
script:
  - "bundle exec rspec"
addons:
  code_climate:
    repo_token: 8259e5b926031e84ed19c7a1a5c42e256fa9a11c2b4cf1457f5a36a45a239ca7
